version: 2
jobs:
  build:
    working_directory: "~/work"
    docker:
      - image: fpco/stack-build:lts-13.13
    steps:
      - checkout
      - restore_cache:
          keys:
            - libraries-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - libraries-{{ checksum "stack.yaml" }}
            - libraries
      - run: stack setup
      - run: stack build --test --only-dependencies
      - save_cache:
          key: libraries-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "~/.stack"
      - run: stack test
