version: 2
jobs:
  build:
    working_directory: "~/work"
    docker:
      - image: haskell:8.6.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - libraries-{{ checksum "package.yaml" }}
            - libraries
      - run: cabal new-update && cabal new-install --overwrite-policy=always hpack
      - run: hpack && HSPEC_OPTIONS=--color cabal new-test
      - save_cache:
          key: libraries-{{ checksum "package.yaml" }}
          paths:
            - "~/.cabal"
